### PR TITLE
Support legacy PHP 5.3

### PR DESCRIPTION
**Pull request by clue**
This (trivial) change allows this library to be used with even older versions of PHP. Note that they may be EOL'ed by Zend, but they're still supported by many common distros / vendors.

Not sure why this was limited to 5.3.29 initially, but I've confirmed this to work with at least 5.3.10 (PHP version in use by Ubuntu 12.04) and possibly below.

### CODE REVIEW

**Comment by kirill-konshin** [comment]
Thanks!

**Comment by clue** [comment]
Thanks for quick reaction @kirill-konshin! Is there an ETA for the next tag so I can start [relying on this](https://github.com/clue/php-buzz-react/issues/16)?

**Comment by kirill-konshin** [comment]
Released 1.2.1. But I strongly recommend to upgrade your version of PHP and stick to original repo, since I don't have any major plans on supporting this fork... Only urgent bugfixes.

**Comment by clue** [comment]
Thanks for the heads up! Unfortunately the upstream maintainer has expressed little interest in supporting legacy PHP versions (which I fully understand and accept), so I'll have to build this on top of this for now.

**Comment by kirill-konshin** [comment]
That was the reason why I forked it :)

**Pull request merged**
